'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Options

    '''<summary>
    '''chkChangeAllButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkChangeAllButtons As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblChangeAllButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChangeAllButtons As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkFillInCalendars control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFillInCalendars As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblFillInCalendars control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFillInCalendars As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkFillInBoxes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFillInBoxes As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblFillInBoxes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFillInBoxes As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkAutoCompleteFix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAutoCompleteFix As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAutoCompleteFix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAutoCompleteFix As Global.DotNetNuke.UI.UserControls.LabelControl
End Class
