'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TestAreaDNN5_Controls

    '''<summary>
    '''lblApplyScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApplyScope As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkApplyScope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkApplyScope As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''dshSection1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dshSection1 As Global.DotNetNuke.UI.UserControls.SectionHeadControl

    '''<summary>
    '''Section1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Section1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''dshSubsection1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dshSubsection1 As Global.DotNetNuke.UI.UserControls.SectionHeadControl

    '''<summary>
    '''Subsection1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Subsection1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''dshSubsection2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dshSubsection2 As Global.DotNetNuke.UI.UserControls.SectionHeadControl

    '''<summary>
    '''Subsection2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Subsection2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''SectionHead2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SectionHead2 As Global.DotNetNuke.UI.UserControls.SectionHeadControl

    '''<summary>
    '''Section2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Section2 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''tblDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDetails As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''rowPerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowPerm As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''dgPermissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgPermissions As Global.DotNetNuke.Security.Permissions.Controls.ModulePermissionsGrid

    '''<summary>
    '''cmdUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpdate As Global.DotNetNuke.UI.WebControls.CommandButton

    '''<summary>
    '''cmdDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDelete As Global.DotNetNuke.UI.WebControls.CommandButton

    '''<summary>
    '''cmdCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancel As Global.DotNetNuke.UI.WebControls.CommandButton

    '''<summary>
    '''ctlCaptcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlCaptcha As Global.DotNetNuke.UI.WebControls.CaptchaControl

    '''<summary>
    '''ctlIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlIcon As Global.DotNetNuke.UI.UserControls.UrlControl

    '''<summary>
    '''ctlModuleContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlModuleContainer As Global.DotNetNuke.UI.Skins.SkinControl

    '''<summary>
    '''TextEditor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextEditor1 As Global.DotNetNuke.UI.UserControls.TextEditor
End Class
