'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NavPanel

    '''<summary>
    '''hlSkinTweakerSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlSkinTweakerSite As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblDemoModeMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDemoModeMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbIntroduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbIntroduction As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbSelectATheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSelectATheme As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbCustomThemes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCustomThemes As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDownload As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbInstall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbInstall As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSelect As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hlInstallation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlInstallation As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lbjQueryScriptEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbjQueryScriptEditor As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbBugHunter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbBugHunter As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblDotNetNukeVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDotNetNukeVersion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSkinTweakerVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSkinTweakerVersion As Global.System.Web.UI.WebControls.Label
End Class
