'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ThemeSelector

    '''<summary>
    '''lblThemes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblThemes As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlThemes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlThemes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbljQueryScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbljQueryScripts As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlScriptSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlScriptSelector As Global.SkinTweaker.ScriptSelector

    '''<summary>
    '''lblApplyCssScopeToPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApplyCssScopeToPage As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlApplyCssScopeToBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlApplyCssScopeToBody As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbApplyThemeNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbApplyThemeNow As Global.System.Web.UI.WebControls.LinkButton
End Class
