'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

    '''<summary>
    '''lblDemoModeON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDemoModeON As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkDemoModeON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDemoModeON As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblDebuggingModeON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDebuggingModeON As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkDebuggingModeON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDebuggingModeON As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblLoggingON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoggingON As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkLoggingON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLoggingON As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlDNN5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDNN5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblAddjQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddjQuery As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''chkAddjQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAddjQuery As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlDNN4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDNN4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbljQueryVersionNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbljQueryVersionNumber As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtjQueryVersionNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtjQueryVersionNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbljQueryUI_VersionNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbljQueryUI_VersionNumber As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''txtjQueryUI_VersionNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtjQueryUI_VersionNumber As Global.System.Web.UI.WebControls.TextBox
End Class
