'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ThemeSelection

    '''<summary>
    '''lblTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTheme As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPortalCssThemeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPortalCssThemeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbljQueryScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbljQueryScripts As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPortaljQueryScriptName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPortaljQueryScriptName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblApplyCssScopeToPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApplyCssScopeToPage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPortalApplyCssScopeToPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPortalApplyCssScopeToPage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ThemeSelector1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThemeSelector1 As Global.SkinTweaker.ThemeSelector

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTestControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTestControls As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlTestControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestControls As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSkinSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSkinSelector As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlSkinSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSkinSelector As Global.SkinTweaker.SkinSelector

    '''<summary>
    '''pnlTestControls1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTestControls1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TestAreajQueryUIControls1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestAreajQueryUIControls1 As Global.SkinTweaker.TestAreajQueryUIControls

    '''<summary>
    '''pnlTestControls4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTestControls4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TestAreaDNN4_Controls1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestAreaDNN4_Controls1 As Global.SkinTweaker.TestAreaDNN4_Controls

    '''<summary>
    '''pnlTestControls5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTestControls5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TestAreaDNN5_Controls1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestAreaDNN5_Controls1 As Global.SkinTweaker.TestAreaDNN5_Controls

    '''<summary>
    '''pnlTestControls6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTestControls6 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TestAreaDNN6_Controls1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestAreaDNN6_Controls1 As Global.SkinTweaker.TestAreaDNN6_Controls

    '''<summary>
    '''pnlTestControls2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTestControls2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TestAreaASP_StandardControls1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestAreaASP_StandardControls1 As Global.SkinTweaker.TestAreaASP_StandardControls

    '''<summary>
    '''pnlTestControls3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTestControls3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TestAreaStandardHTML1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestAreaStandardHTML1 As Global.SkinTweaker.TestAreaStandardHTML
End Class
